In [1]:
#conda install pandas

In [2]:
#conda install numpy

In [1]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

In [2]:
#import numpy as np   #1
#import pandas as pd  #1
#import tensorflow as tf

#from tensorflow.keras import datasets, layers, models

In [2]:
#expression_df=pd.read_csv("data/final_expression_matrix.csv")  #1
expression_df=pd.read_csv("data/brown_moduel_final_expression_matrix_protein_coding_genes.csv")  #这里是获取表达矩阵  222是简化版的表达矩阵，去掉了未包含基因的表达  #1
#expression_df

In [3]:
expression_df=expression_df.iloc[:,1:]   #处理后的表达矩阵  #1
expression_df

NMU      MPP6     HELLS  SERPINH1      MMP1     CDC45    RECQL4  \
0    1.988758  2.410974  2.554973  2.938907  2.925223  2.202006  2.916986   
1    2.530752  2.465955  2.921754  2.700343  3.020211  2.191164  2.466335   
2    2.938681  3.168721  2.736002  3.571388  3.317052  3.218561  3.039234   
3    3.321870  2.877472  3.286556  3.486865  3.557687  3.233609  3.019145   
4    2.886046  2.854868  2.613107  3.704406  3.241178  2.332050  2.561400   
..        ...       ...       ...       ...       ...       ...       ...   
503  2.488856  2.534030  2.254817  3.145851  2.105945  2.466984  2.462443   
504  2.084529  2.638165  2.645124  3.284945  1.856186  2.778333  3.045060   
505  2.983445  2.886324  2.378262  3.578735  3.286223  2.308473  3.075204   
506  2.389925  2.498607  2.090926  3.712644  2.839805  2.341657  2.177574   
507  3.010042  2.640321  2.800470  3.365595  2.112131  2.986731  2.472796   

      CYP39A1    MAGOHB     LRFN4  ...     VPS11   EFCAB14    STAMBP  \
0    1.775309  2.418019  3.217036  ...  3.363723  3.650818  3.455322   
1    2.685280  2.534429  2.501178  ...  3.323100  3.711899  3.420003   
2    2.883078  3.251888  3.261916  ...  3.368445  3.599298  3.461157   
3    2.885689  3.101316  2.661579  ...  3.267558  3.555324  3.389009   
4    2.525025  3.120846  2.700056  ...  3.342189  3.677561  3.355134   
..        ...       ...       ...  ...       ...       ...       ...   
503  2.860631  2.483522  2.480105  ...  3.413649  3.689426  3.435815   
504  2.895367  2.629861  3.463325  ...  3.284773  3.604859  3.444399   
505  2.678983  3.048118  3.171238  ...  3.326332  3.648799  3.459115   
506  2.706542  2.524672  2.708074  ...  3.400943  3.686900  3.393673   
507  1.522595  2.788118  2.522431  ...  3.391269  3.685196  3.440335   

      ANAPC13      NARS     SRSF3      POP4       UBC    TARDBP      MYL6  
0    3.662846  3.767023  3.651851  3.423086  4.100721  3.580811  3.926669  
1    3.644896  3.689478  3.657553  3.475010  4.099053  3.572318  3.913141  
2    3.598038  3.816763  3.676692  3.577377  4.042208  3.605396  3.906802  
3    3.666805  3.826251  3.653783  3.502168  4.038297  3.641708  3.919966  
4    3.588625  3.714582  3.676957  3.459504  4.075292  3.568624  3.979495  
..        ...       ...       ...       ...       ...       ...       ...  
503  3.706207  3.694033  3.717823  3.433686  4.077429  3.545890  3.929556  
504  3.591315  3.818162  3.739648  3.390711  4.042627  3.566084  3.910765  
505  3.652235  3.726065  3.671684  3.446329  4.010623  3.592149  3.879138  
506  3.717705  3.662509  3.682267  3.503398  4.051515  3.581591  3.947246  
507  3.660167  3.760988  3.697090  3.483746  4.076447  3.539539  3.946215  

[508 rows x 777 columns]

In [4]:
#Interaction_df=pd.read_csv("data/string_interactions_short.tsv",sep='\t')  #1  这个是只有正样本的情况
Interaction_df=pd.read_csv("brown_final_interaction_positive_negative_1_1.csv")
#Interaction_df

In [5]:
Interaction_df=Interaction_df.iloc[:,[0,1,-1]]  #简化版的相互作用  #1
Interaction_df

node1   node2  label
0      BUB1B    SKA1      1
1      ANOS1   GINS1      0
2      FANCI     ME3      0
3      KIF4A  CHCHD3      0
4       MCM6   SSRP1      1
...      ...     ...    ...
9575  GALNT3    E2F8      0
9576   BBOF1   H2AZ2      0
9577   MTPAP    CDK1      0
9578    YES1   CPSF6      0
9579   KIF15    SMC4      1

[9580 rows x 3 columns]

In [6]:
gene_map_protein=pd.read_csv("data/brownModule_string_mapping_revise.tsv",sep='\t')  #1
gene_map_protein=gene_map_protein.iloc[:,1:]    #这个就是基因和PPI网络的映射关系   #1
gene_map_list=gene_map_protein.iloc[:,0]    #gene列表   #1
protein_map_list=gene_map_protein.iloc[:,1]  #protein列表  #1

In [7]:
gene_map_list

0           NMU
1          MPP6
2         HELLS
3      SERPINH1
4          MMP1
         ...   
767       SRSF3
768        POP4
769         UBC
770      TARDBP
771        MYL6
Name: queryItem, Length: 772, dtype: object

In [8]:
protein_map_list

0           NMU
1          MPP6
2         HELLS
3      SERPINH1
4          MMP1
         ...   
767       SRSF3
768        POP4
769         UBC
770      TARDBP
771        MYL6
Name: preferredName, Length: 772, dtype: object

In [9]:
Interaction_1=Interaction_df["node1"]  #1
Interaction_2=Interaction_df["node2"]   #1
Interaction_1=Interaction_1.values     #1
Interaction_2=Interaction_2.values   #这里将相互作用的两个端点分别存储在两个array中，后续利用循环遍历每一对关系  #1
label_list=Interaction_df["label"]    #1

In [10]:
a=Interaction_1[0]   #这里是做个实验，同时发现一个问题，相互作用的端点基因在表达矩阵中，可以基因的名字不一样，例如在相互作用中记录
                        #的是AARS,但是在表达矩阵，记录的是AARS1
b=Interaction_2[0]
print(a,b)

BUB1B SKA1


In [11]:
gene_index=expression_df.columns   #这里将表达矩阵的基因索引单独存放在一个array中   #1
gene_index=np.array(gene_index)     #1
gene_index

array(['NMU', 'MPP6', 'HELLS', 'SERPINH1', 'MMP1', 'CDC45', 'RECQL4',
       'CYP39A1', 'MAGOHB', 'LRFN4', 'PLIN1', 'DUSP2', 'FOXD1', 'CDCA8',
       'MICAL3', 'ZNF532', 'CENPE', 'OR7E47P', 'KIFC1', 'RAD54L', 'NCAPH',
       'PRR3', 'NDC80', 'LGALSL', 'HOXB2', 'GCNT2', 'APOD', 'KIF18A',
       'MYBL2', 'TRMU', 'MCM10', 'PLAT', 'ERCC6L', 'CDCA3', 'RASAL2',
       'MAOA', 'POLA2', 'WLS', 'SLITRK5', 'CFD', 'KIF23', 'ZNF696',
       'HOMER1', 'PAK1IP1', 'TTK', 'E2F5', 'CENPI', 'CBR1', 'NETO2',
       'RPL39L', 'TRAIP', 'FKBP1B', 'TACC3', 'FOXM1', 'C16orf95', 'SKA1',
       'RAD51AP1', 'PTGER3', 'ASPM', 'CPA3', 'SLC7A5', 'MYBL1', 'WFDC2',
       'CREB3L1', 'TAT', 'CCNE1', 'PLOD2', 'INHBB', 'NEK2', 'MAD2L1',
       'CEP55', 'PRIM2', 'SRD5A1', 'ARHGEF9', 'IMPA2', 'NASP', 'CIB2',
       'GINS4', 'NUDT18', 'GGH', 'E2F8', 'EZH2', 'GALNT3', 'CDC20',
       'MELK', 'ORC1', 'PTTG3P', 'RTN1', 'SLMO1', 'CST3', 'CBX7',
       'APOBEC3B', 'IGFBP6', 'PBK', 'MYC', 'AGTR1', 'FBXO5', 'TPSB2',
       'CCNE2

In [12]:
index_1=np.where(gene_index==a)#这里是为了得到具有相互作用的两个基因在基因表达矩阵中对应的索引，有了索引，才能得到该基因在所有样本中的表达情况
index_2=np.where(gene_index==b)
print(index_1,index_2)

(array([279], dtype=int64),) (array([55], dtype=int64),)


In [13]:
index_1[0]

array([279], dtype=int64)

In [14]:
index_1[0].size   #index_1是一个元组，存放的是一个np.ndarray。

1

In [15]:
index_2[0].size

1

In [16]:
if((index_1[0].size)!=1):
    index=np.where(protein_map_list==a)
    print(index[0].size)
    a=gene_map_list[index[0][0]]   #若是


In [17]:
a

'BUB1B'

In [18]:
index_1=np.where(gene_index==a)
index_1

(array([279], dtype=int64),)

In [19]:
expression_matrix=expression_df.values  #这里将df形式的表达矩阵转为array，方便用numpy进行运算   #1
expression_matrix.shape

(508, 777)

In [21]:
gene_1_expression=expression_matrix[:,index_1].reshape(508)   #这里是获取某一个相互关系的一个端点基因的表达情况 1173是样本数

In [22]:
gene_1_expression.max()

3.5857222955293

In [23]:
gene_1_expression.min()

2.36004847157738

In [24]:
equipartition_1=np.linspace(gene_1_expression.min(),gene_1_expression.max(),num=33)    #这里是将基因表达情况32等分，和另一个基因的情况执行共出现概率分布，转变为图像
equipartition_1

array([2.36004847, 2.39835078, 2.43665309, 2.47495539, 2.5132577 ,
       2.55156001, 2.58986231, 2.62816462, 2.66646693, 2.70476923,
       2.74307154, 2.78137385, 2.81967616, 2.85797846, 2.89628077,
       2.93458308, 2.97288538, 3.01118769, 3.04949   , 3.0877923 ,
       3.12609461, 3.16439692, 3.20269923, 3.24100153, 3.27930384,
       3.31760615, 3.35590845, 3.39421076, 3.43251307, 3.47081537,
       3.50911768, 3.54741999, 3.5857223 ])

In [25]:
gene_2_expression=expression_matrix[:,index_2].reshape(508)   #这里是获取某一个相互关系的第二个端点基因的表达情况
equipartition_2=np.linspace(gene_2_expression.min(),gene_2_expression.max(),num=33)    #这里是将基因表达情况32等分，和另一个基因的情况执行共出现概率分布，转变为图像

In [26]:
#这里通过numpy.histogram2d方法进行转换，将两个基因的表达情况转变为图像
H,x_edges,y_edges=np.histogram2d(gene_1_expression,gene_2_expression,bins=32)
H.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 6., 0., 0.],
       [0., 0., 0., ..., 2., 3., 0.],
       [0., 0., 0., ..., 3., 0., 0.]])

In [27]:
10**-2

0.01

In [28]:
x_edges

array([2.36004847, 2.39835078, 2.43665309, 2.47495539, 2.5132577 ,
       2.55156001, 2.58986231, 2.62816462, 2.66646693, 2.70476923,
       2.74307154, 2.78137385, 2.81967616, 2.85797846, 2.89628077,
       2.93458308, 2.97288538, 3.01118769, 3.04949   , 3.0877923 ,
       3.12609461, 3.16439692, 3.20269923, 3.24100153, 3.27930384,
       3.31760615, 3.35590845, 3.39421076, 3.43251307, 3.47081537,
       3.50911768, 3.54741999, 3.5857223 ])

In [29]:
np.sum(H)

508.0

In [30]:
#将转变图像的代码封装成函数形式   #1
def transform_image(gene1_name,gene2_name,gene_list,expression_matrix):   #这里传入的gene_list是表达矩阵中基因的顺序(不能修改)，传入的expression_matrix是array类型的
    index_1=np.where(gene_list==gene1_name)#这里是为了得到具有相互作用的两个基因在基因表达矩阵中对应的索引，有了索引，才能得到该基因在所有样本中的表达情况
    if((index_1[0].size)!=1):  # 如果未找到和蛋白质名相同的基因，就找蛋白质在ppi网络中映射的基因
        index=np.where(protein_map_list==gene1_name)#在蛋白质列表找到对应的下标
        if index[0].size>0:   #找到了蛋白质映射的基因名
            gene1_name=gene_map_list[index[0][0]]
            index_1=np.where(gene_list==gene1_name)  #找到gene名在表达矩阵对应的表达向量的索引
    index_2=np.where(gene_list==gene2_name)
    if((index_2[0].size)!=1):
        index=np.where(protein_map_list==gene2_name)
        if index[0].size>0:
            gene2_name=gene_map_list[index[0][0]]
            index_2=np.where(gene_list==gene2_name)
    if(index_1[0].size>0 and index_2[0].size>0):
        gene_1_expression=expression_matrix[:,index_1].reshape(508)   #这里是获取某一个相互关系的一个端点基因的表达情况   这里的1166是样本数，reshape是为了降低维度
       
        gene_2_expression=expression_matrix[:,index_2].reshape(508)   #这里是获取某一个相互关系的第二个端点基因的表达情况
        #这里通过numpy.histogram2d方法进行转换，将两个基因的表达情况转变为图像
        H,x_edges,y_edges=np.histogram2d(gene_1_expression,gene_2_expression,bins=32)
        H=H.T
        print(H.sum())
        #H=(np.log10(H/1166+10**-4)+4)/4      #这里是对每一个基因对图像的值做类似降维的处理，防止值过大
        print(H.sum())
        #print(H)
        return H
    else :
        return 0 

In [31]:
a=transform_image("KIF23","TROAP",gene_index,expression_matrix)   #测试转变图像的函数
a.shape

508.0
508.0


(32, 32)

In [32]:
#transform_image("AARS","TARS2",gene_index,expression_matrix)      #测试转变图像的函数

In [33]:
#根据转变图像的函数，和已知的关联，生成数据及其标签
#Interaction_1 关联的基因对的节点1
#Interaction_2  关联的基因对的节点2
label_list       #关联的标签

0       1
1       0
2       0
3       0
4       1
       ..
9575    0
9576    0
9577    0
9578    0
9579    1
Name: label, Length: 9580, dtype: int64

In [36]:
#image_data=(transform_image(Interaction_1[0],Interaction_2[0],gene_index,expression_matrix))
#print(image_data.sum())
#print(image_data.shape)
#image_data=np.append(image_data,values=transform_image(Interaction_1[1],Interaction_2[1],gene_index,expression_matrix))
#image_data.reshape(2,32,32)
#print(image_data.shape)

In [34]:
label=label_list.values.reshape(9580 ,1)
print(label[0])
print(label.shape)
image_data=np.array(transform_image(Interaction_1[0],Interaction_2[0],gene_index,expression_matrix))
print(image_data.sum())
label_data=np.array(label[0])
print(image_data.shape)
print(label_data.shape)

[1]
(9580, 1)
508.0
508.0
508.0
(32, 32)
(1,)


In [35]:
for i in range(1,9580):     #i 0-5999  开始的第一个关系已经记录
    gene1_name=Interaction_1[i]
    gene2_name=Interaction_2[i]
    #label=label_list[i]
    H=transform_image(gene1_name,gene2_name,gene_index,expression_matrix)
    if type(H)==np.ndarray:
        #print(H.sum())
        #H=np.log2(H)         #对转变后的图像数据，进行Log运算，去除极端值
        #print(H.sum())
        image_data=np.append(image_data,values=H)
        label_data=np.append(label_data,values=label[i])

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.0
508.

In [36]:
image_data.shape   #代表12098张 32x32的图像

(9809920,)

In [37]:
#将图像数据写入文件
image_data.tofile('brownModule_interaction_Image_data_1_1.csv',sep=',')

In [38]:
label_data.shape

(9580,)

In [39]:
#将标签写入文件
label_data.tofile('brownModule_interaction_Image_data_label_1_1.csv',sep=',')